### ISSUE TITLE
Orientation Issues

### ISSUE THREAD

**Issue by SMB47** [Awalz/SwiftyCam#74]
I'm getting some orientation issues if I load my app with the iPad in landscape mode. If I tap-to-focus, the preview turns by 90 degrees. This also happens when I tap the button to take the photo (see attached example). Can you please help?

![img_0003](https://user-images.githubusercontent.com/29151724/27484047-a7bd76aa-581f-11e7-9e56-58af371ea194.jpg)

![img_0004](https://user-images.githubusercontent.com/29151724/27484057-ae815812-581f-11e7-8861-71fa7373e943.jpg)

**Comment by Awalz** [comment]
Issue should be resolved in version 2.6.0

**Comment by porzal** [comment]
When will 2.6.0 be out? I just downloaded the zipped file from this and I am still seeing this same issue.
